name: Deploy the backend
on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: abhassen/todo-app-backend:${{ github.sha }}
    - name: Deploy to the VM
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.201.119.15 << 'EOF'
            sudo docker stop user_backend || true
            sudo docker rm user_backend || true
            sudo docker pull abhassen/todo-app-backend:${{ github.sha }}
            sudo docker run --name user_backend -d -p 8080:8080 --restart=unless-stopped abhassen/todo-app-backend:${{ github.sha }}
          EOF